10  TEXT : HOME
20  D$ =  CHR$ (4)
30  PRINT "APPLE II SSC -> CENTRONICS GLP 3101"
40  PRINT "SERIAL TEST DISK - CARD IN SLOT 2"
50  PRINT
60  PRINT "1  LOOPBACK   TEST THE CARD BY ITSELF"
70  PRINT "2  FRAMING    FIND DATA/PARITY/STOP"
80  PRINT "3  BAUD       FIND THE BAUD RATE"
90  PRINT "4  SMOKETEST  FULL PRINTER TEST"
100  PRINT "5  RXWATCH    SHOW BYTES FROM PRINTER"
105  PRINT "6  DIRECT     PRINT WITHOUT THE FIRMWARE"
107  PRINT "7  STDTEST    NORMAL PR#2 PATH + TEST"
108  PRINT "8  PRSETUP    JUST CONFIGURE, NO TEST"
110  PRINT
120  PRINT "Q  QUIT TO BASIC"
130  PRINT
140  PRINT "CHOICE ";
150  GET A$
160  PRINT A$
170  IF A$ = "1" THEN  PRINT D$;"RUN LOOPBACK"
180  IF A$ = "2" THEN  PRINT D$;"RUN FRAMING"
190  IF A$ = "3" THEN  PRINT D$;"RUN BAUD"
200  IF A$ = "4" THEN  PRINT D$;"RUN SMOKETEST"
210  IF A$ = "5" THEN  PRINT D$;"RUN RXWATCH"
215  IF A$ = "6" THEN  PRINT D$;"RUN DIRECT"
217  IF A$ = "7" THEN  PRINT D$;"RUN STDTEST"
218  IF A$ = "8" THEN  PRINT D$;"RUN PRSETUP"
220  IF A$ = "Q" THEN  END
230  GOTO 10
